/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc
 */
public class Programicianaekran extends javax.swing.JFrame {

    /**
     * Creates new form Programicianaekran
     */
    public Programicianaekran() {
        initComponents();
    }
    String seciliisyeriadi;

    String dosya = "c:\\dosyalar\\Islemler.txt";

    public Programicianaekran(String s) {
        initComponents();
        seciliisyeriadi = s;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        alisfaturasibuton = new javax.swing.JButton();
        satisfaturasibuton = new javax.swing.JButton();
        carihareketbuton = new javax.swing.JButton();
        cariextrebuton = new javax.swing.JButton();
        tumextrebuton = new javax.swing.JButton();
        caridetaybuton = new javax.swing.JButton();
        stokdetaybuton = new javax.swing.JButton();
        stokkaydibuton = new javax.swing.JButton();
        carikaydibuton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alisfaturasibuton.setText("Alis Faturasi");
        alisfaturasibuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alisfaturasibutonActionPerformed(evt);
            }
        });

        satisfaturasibuton.setText("Satis Faturasi");
        satisfaturasibuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisfaturasibutonActionPerformed(evt);
            }
        });

        carihareketbuton.setText("Hareket Kaydi");
        carihareketbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carihareketbutonActionPerformed(evt);
            }
        });

        cariextrebuton.setText("Cariye Ait Hesap Ekstre");
        cariextrebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariextrebutonActionPerformed(evt);
            }
        });

        tumextrebuton.setText("Tum Ekstre");
        tumextrebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tumextrebutonActionPerformed(evt);
            }
        });

        caridetaybuton.setText("Cari Detaylari");
        caridetaybuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caridetaybutonActionPerformed(evt);
            }
        });

        stokdetaybuton.setText("Stok Detaylari");
        stokdetaybuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokdetaybutonActionPerformed(evt);
            }
        });

        stokkaydibuton.setText("Stok Kaydi");
        stokkaydibuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokkaydibutonActionPerformed(evt);
            }
        });

        carikaydibuton.setText("Cari Kaydi");
        carikaydibuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carikaydibutonActionPerformed(evt);
            }
        });

        jButton1.setText("Tum Stoklar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jButton2.setText("Tum Cariler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ANA MENU");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Kayıt Islemleri");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Alisveris Islemleri");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("İslem Bilgileri");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Stok - Cari Bilgileri");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(caridetaybuton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(stokdetaybuton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(carikaydibuton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stokkaydibuton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tumextrebuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cariextrebuton)))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(alisfaturasibuton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carihareketbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satisfaturasibuton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alisfaturasibuton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(satisfaturasibuton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(carihareketbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cariextrebuton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokkaydibuton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tumextrebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carikaydibuton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(caridetaybuton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokdetaybuton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alisfaturasibutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisfaturasibutonActionPerformed

        AlisStok stokcarisec = new AlisStok(seciliisyeriadi);
        stokcarisec.setVisible(rootPaneCheckingEnabled);


    }//GEN-LAST:event_alisfaturasibutonActionPerformed

    private void satisfaturasibutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisfaturasibutonActionPerformed

        SatisStok stokcarisec2 = new SatisStok(seciliisyeriadi);
        stokcarisec2.setVisible(rootPaneCheckingEnabled);


    }//GEN-LAST:event_satisfaturasibutonActionPerformed

    private void carihareketbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carihareketbutonActionPerformed

        Carihareketkaydi carihareketkaydi = new Carihareketkaydi(seciliisyeriadi);
        carihareketkaydi.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_carihareketbutonActionPerformed

    private void cariextrebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariextrebutonActionPerformed
        // TODO add your handling code here:

        Carihesapekstre1 carihesapekstre1 = new Carihesapekstre1(seciliisyeriadi);
        carihesapekstre1.setVisible(rootPaneCheckingEnabled);


    }//GEN-LAST:event_cariextrebutonActionPerformed

    private void tumextrebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tumextrebutonActionPerformed
        // TODO add your handling code here:
        Tumekstre tumekstre = new Tumekstre(seciliisyeriadi);
        tumekstre.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_tumextrebutonActionPerformed


    private void caridetaybutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caridetaybutonActionPerformed
        // TODO add your handling code here:

        Caridetay1 caridty1 = new Caridetay1(seciliisyeriadi);
        caridty1.setVisible(rootPaneCheckingEnabled);


    }//GEN-LAST:event_caridetaybutonActionPerformed

    private void stokdetaybutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokdetaybutonActionPerformed
        // TODO add your handling code here:

        Stokdetay1 stokdty1 = new Stokdetay1(seciliisyeriadi);
        stokdty1.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_stokdetaybutonActionPerformed


    private void stokkaydibutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokkaydibutonActionPerformed
        // TODO add your handling code here:

        Stokkaydi stokkaydi = new Stokkaydi(seciliisyeriadi);

        stokkaydi.setVisible(rootPaneCheckingEnabled);


    }//GEN-LAST:event_stokkaydibutonActionPerformed

    private void carikaydibutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carikaydibutonActionPerformed
        // TODO add your handling code here:

        CariKaydi carikaydiframe = new CariKaydi(seciliisyeriadi);
        carikaydiframe.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_carikaydibutonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TumStoklar tumstoklar = new TumStoklar(seciliisyeriadi);
        tumstoklar.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TumCariler tumcariler = new TumCariler(seciliisyeriadi);
        tumcariler.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programicianaekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programicianaekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programicianaekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programicianaekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programicianaekran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alisfaturasibuton;
    private javax.swing.JButton caridetaybuton;
    private javax.swing.JButton cariextrebuton;
    private javax.swing.JButton carihareketbuton;
    private javax.swing.JButton carikaydibuton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton satisfaturasibuton;
    private javax.swing.JButton stokdetaybuton;
    private javax.swing.JButton stokkaydibuton;
    private javax.swing.JButton tumextrebuton;
    // End of variables declaration//GEN-END:variables
}
